name: montreal
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pytorch>=2.0
  - torchvision
  - numpy
  - matplotlib
  - jupyter
  - notebook
  - pip
  - pip:
      - tqdm
